//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENI
{
    using System;
    using System.Collections.Generic;
    
    public partial class display
    {
        public int id { get; set; }
        public string name { get; set; }
        public string token { get; set; }
        public string location { get; set; }
        public Nullable<int> orientation { get; set; }
        public string display_size { get; set; }
        public string timetable { get; set; }
        public bool is_active { get; set; }
        public Nullable<System.DateTime> last_activity_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> last_modified_date { get; set; }
        public Nullable<int> playlist_update_interval { get; set; }
        public Nullable<int> report_update_interval { get; set; }
    }
}
