//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eniEntities : DbContext
    {
        public eniEntities()
            : base("name=eniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<display> display { get; set; }
        public virtual DbSet<media> media { get; set; }
        public virtual DbSet<modules> modules { get; set; }
        public virtual DbSet<report> report { get; set; }
        public virtual DbSet<report_insertions> report_insertions { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<user_role_permission> user_role_permission { get; set; }
    }
}
