//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENI
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_insertions
    {
        public int id { get; set; }
        public Nullable<int> media_id { get; set; }
        public string media_name { get; set; }
        public Nullable<int> display_id { get; set; }
        public string display_token { get; set; }
        public string display_location { get; set; }
        public string display_orientation { get; set; }
        public string display_size { get; set; }
        public Nullable<int> insertions_counted { get; set; }
        public Nullable<System.DateTime> period_start_date { get; set; }
        public Nullable<System.DateTime> period_end_date { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual display display { get; set; }
        public virtual media media { get; set; }
    }
}
