//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENI
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public Nullable<int> user_role_id { get; set; }
        public string name { get; set; }
        public string user_picture_url { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> token_expiration_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> last_modified_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_super_user { get; set; }
    
        public virtual user_role user_role { get; set; }
    }
}
