//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENI
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role_permission
    {
        public int id { get; set; }
        public int user_role_id { get; set; }
        public int module_id { get; set; }
        public Nullable<bool> can_read { get; set; }
        public Nullable<bool> can_write { get; set; }
        public Nullable<bool> can_delete { get; set; }
        public bool is_active { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual modules modules { get; set; }
        public virtual user_role user_role { get; set; }
    }
}
